name: Jekife
title: Jekife | un site pour trouver un parrain
description: Jekife est un site pour trouver un parrain chez Boursorama, ING,
  Planete Oui, Pretup, Sosh
tags:
  - parrain
  - parrainage
  - gain
  - euros
  - boursorama
  - ing
  - pretup
  - sosh
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: pubrondeau@gmail.com
disqus_username: ""
translations :
  button:
     read_now: Voir
 recommendation :
     text : Pourquoi ne pas lire un autre article?
     back_btn : Retour en haut
